/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerDTO = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InvoiceItem = IDL.Record({
  'weight' : IDL.Float64,
  'total' : IDL.Float64,
  'rate' : IDL.Float64,
  'description' : IDL.Text,
  'purity' : IDL.Float64,
});
export const InvoiceDTO = IDL.Record({
  'gst' : IDL.Bool,
  'gstPercent' : IDL.Float64,
  'language' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : IDL.Text,
  'items' : IDL.Vec(InvoiceItem),
  'partialPayment' : IDL.Float64,
});
export const Time = IDL.Int;
export const JobOrderDTO = IDL.Record({
  'customerName' : IDL.Text,
  'assignedKaragir' : IDL.Text,
  'dueDate' : Time,
  'description' : IDL.Text,
});
export const Role = IDL.Variant({
  'karagir' : IDL.Null,
  'manager' : IDL.Null,
  'owner' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserDTO = IDL.Record({
  'password' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'phone' : IDL.Text,
});
export const Customer = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const GoldRateDTO = IDL.Record({ 'ratePerGram' : IDL.Float64 });
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'gst' : IDL.Bool,
  'status' : IDL.Variant({
    'paid' : IDL.Null,
    'locked' : IDL.Null,
    'draft' : IDL.Null,
    'partial' : IDL.Null,
  }),
  'createdAt' : Time,
  'gstPercent' : IDL.Float64,
  'amountPaid' : IDL.Float64,
  'language' : IDL.Text,
  'updatedAt' : Time,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'udhar' : IDL.Float64,
  'customerId' : IDL.Text,
  'items' : IDL.Vec(InvoiceItem),
  'partialPayment' : IDL.Float64,
});
export const JobOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'assignedKaragir' : IDL.Text,
  'createdAt' : Time,
  'dueDate' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'notes' : IDL.Text,
});
export const SettingsDTO = IDL.Record({
  'gstNumber' : IDL.Text,
  'address' : IDL.Text,
  'defaultLanguage' : IDL.Text,
  'shopName' : IDL.Text,
  'phone' : IDL.Text,
});
export const InvoiceUpdateDTO = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'paid' : IDL.Null,
    'locked' : IDL.Null,
    'draft' : IDL.Null,
    'partial' : IDL.Null,
  }),
});
export const JobOrderUpdateDTO = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([CustomerDTO], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInvoice' : IDL.Func([InvoiceDTO], [IDL.Text], []),
  'createJobOrder' : IDL.Func([JobOrderDTO], [IDL.Text], []),
  'createUser' : IDL.Func([UserDTO], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(CustomerDTO)], ['query']),
  'getGoldRate' : IDL.Func([], [GoldRateDTO], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
  'getInvoiceCounts' : IDL.Func(
      [],
      [IDL.Record({ 'total' : IDL.Nat, 'paid' : IDL.Nat, 'unpaid' : IDL.Nat })],
      ['query'],
    ),
  'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getInvoicesByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Invoice)], ['query']),
  'getJobOrder' : IDL.Func([IDL.Text], [IDL.Opt(JobOrder)], ['query']),
  'getJobOrders' : IDL.Func([], [IDL.Vec(JobOrder)], ['query']),
  'getPaidInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getPaymentHistory' : IDL.Func([IDL.Text], [IDL.Vec(Invoice)], ['query']),
  'getSettings' : IDL.Func([], [SettingsDTO], ['query']),
  'getTotalSales' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalUdharPending' : IDL.Func([], [IDL.Float64], ['query']),
  'getUdharLedger' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getUnpaidInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'lockInvoice' : IDL.Func([IDL.Text], [], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [UserDTO], []),
  'receivePayment' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGoldRate' : IDL.Func([GoldRateDTO], [], []),
  'updateInvoiceStatus' : IDL.Func([InvoiceUpdateDTO], [], []),
  'updateJobOrder' : IDL.Func([JobOrderUpdateDTO], [], []),
  'updateSettings' : IDL.Func([SettingsDTO], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerDTO = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InvoiceItem = IDL.Record({
    'weight' : IDL.Float64,
    'total' : IDL.Float64,
    'rate' : IDL.Float64,
    'description' : IDL.Text,
    'purity' : IDL.Float64,
  });
  const InvoiceDTO = IDL.Record({
    'gst' : IDL.Bool,
    'gstPercent' : IDL.Float64,
    'language' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : IDL.Text,
    'items' : IDL.Vec(InvoiceItem),
    'partialPayment' : IDL.Float64,
  });
  const Time = IDL.Int;
  const JobOrderDTO = IDL.Record({
    'customerName' : IDL.Text,
    'assignedKaragir' : IDL.Text,
    'dueDate' : Time,
    'description' : IDL.Text,
  });
  const Role = IDL.Variant({
    'karagir' : IDL.Null,
    'manager' : IDL.Null,
    'owner' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserDTO = IDL.Record({
    'password' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'phone' : IDL.Text,
  });
  const Customer = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GoldRateDTO = IDL.Record({ 'ratePerGram' : IDL.Float64 });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'gst' : IDL.Bool,
    'status' : IDL.Variant({
      'paid' : IDL.Null,
      'locked' : IDL.Null,
      'draft' : IDL.Null,
      'partial' : IDL.Null,
    }),
    'createdAt' : Time,
    'gstPercent' : IDL.Float64,
    'amountPaid' : IDL.Float64,
    'language' : IDL.Text,
    'updatedAt' : Time,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'udhar' : IDL.Float64,
    'customerId' : IDL.Text,
    'items' : IDL.Vec(InvoiceItem),
    'partialPayment' : IDL.Float64,
  });
  const JobOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'assignedKaragir' : IDL.Text,
    'createdAt' : Time,
    'dueDate' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'notes' : IDL.Text,
  });
  const SettingsDTO = IDL.Record({
    'gstNumber' : IDL.Text,
    'address' : IDL.Text,
    'defaultLanguage' : IDL.Text,
    'shopName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InvoiceUpdateDTO = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'paid' : IDL.Null,
      'locked' : IDL.Null,
      'draft' : IDL.Null,
      'partial' : IDL.Null,
    }),
  });
  const JobOrderUpdateDTO = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'notes' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([CustomerDTO], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInvoice' : IDL.Func([InvoiceDTO], [IDL.Text], []),
    'createJobOrder' : IDL.Func([JobOrderDTO], [IDL.Text], []),
    'createUser' : IDL.Func([UserDTO], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(CustomerDTO)], ['query']),
    'getGoldRate' : IDL.Func([], [GoldRateDTO], ['query']),
    'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
    'getInvoiceCounts' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'paid' : IDL.Nat,
            'unpaid' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getInvoicesByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getJobOrder' : IDL.Func([IDL.Text], [IDL.Opt(JobOrder)], ['query']),
    'getJobOrders' : IDL.Func([], [IDL.Vec(JobOrder)], ['query']),
    'getPaidInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getPaymentHistory' : IDL.Func([IDL.Text], [IDL.Vec(Invoice)], ['query']),
    'getSettings' : IDL.Func([], [SettingsDTO], ['query']),
    'getTotalSales' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalUdharPending' : IDL.Func([], [IDL.Float64], ['query']),
    'getUdharLedger' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getUnpaidInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'lockInvoice' : IDL.Func([IDL.Text], [], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [UserDTO], []),
    'receivePayment' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGoldRate' : IDL.Func([GoldRateDTO], [], []),
    'updateInvoiceStatus' : IDL.Func([InvoiceUpdateDTO], [], []),
    'updateJobOrder' : IDL.Func([JobOrderUpdateDTO], [], []),
    'updateSettings' : IDL.Func([SettingsDTO], [], []),
  });
};

export const init = ({ IDL }) => { return []; };