/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CustomerDTO = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomOrderDTO = IDL.Record({
  'customerName' : IDL.Text,
  'itemDescription' : IDL.Text,
  'designNotes' : IDL.Text,
  'dueDate' : Time,
  'advancePaid' : IDL.Float64,
  'phone' : IDL.Text,
  'estimatedCost' : IDL.Float64,
  'referenceImageHash' : IDL.Opt(IDL.Text),
});
export const InvoiceItem = IDL.Record({
  'weight' : IDL.Float64,
  'total' : IDL.Float64,
  'rate' : IDL.Float64,
  'description' : IDL.Text,
  'purity' : IDL.Float64,
});
export const InvoiceDTO = IDL.Record({
  'gst' : IDL.Bool,
  'gstPercent' : IDL.Float64,
  'language' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : IDL.Text,
  'items' : IDL.Vec(InvoiceItem),
  'partialPayment' : IDL.Float64,
});
export const JobOrderDTO = IDL.Record({
  'customerName' : IDL.Text,
  'assignedKaragir' : IDL.Text,
  'dueDate' : Time,
  'description' : IDL.Text,
});
export const RepairOrderDTO = IDL.Record({
  'customerName' : IDL.Text,
  'itemDescription' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'estimatedCost' : IDL.Float64,
  'referenceImageHash' : IDL.Opt(IDL.Text),
});
export const Role = IDL.Variant({
  'karagir' : IDL.Null,
  'manager' : IDL.Null,
  'owner' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserDTO = IDL.Record({
  'password' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'phone' : IDL.Text,
});
export const CustomOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Variant({
    'delivered' : IDL.Null,
    'inProgress' : IDL.Null,
    'received' : IDL.Null,
    'ready' : IDL.Null,
  }),
  'itemDescription' : IDL.Text,
  'createdAt' : Time,
  'designNotes' : IDL.Text,
  'dueDate' : Time,
  'updatedAt' : Time,
  'advancePaid' : IDL.Float64,
  'phone' : IDL.Text,
  'estimatedCost' : IDL.Float64,
  'referenceImageHash' : IDL.Opt(IDL.Text),
});
export const Customer = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const GoldRateDTO = IDL.Record({ 'ratePerGram' : IDL.Float64 });
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'gst' : IDL.Bool,
  'status' : IDL.Variant({
    'paid' : IDL.Null,
    'locked' : IDL.Null,
    'draft' : IDL.Null,
    'partial' : IDL.Null,
  }),
  'createdAt' : Time,
  'gstPercent' : IDL.Float64,
  'amountPaid' : IDL.Float64,
  'language' : IDL.Text,
  'updatedAt' : Time,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'udhar' : IDL.Float64,
  'customerId' : IDL.Text,
  'items' : IDL.Vec(InvoiceItem),
  'partialPayment' : IDL.Float64,
});
export const JobOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'assignedKaragir' : IDL.Text,
  'createdAt' : Time,
  'dueDate' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'notes' : IDL.Text,
});
export const RepairOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Variant({
    'delivered' : IDL.Null,
    'inProgress' : IDL.Null,
    'received' : IDL.Null,
    'ready' : IDL.Null,
  }),
  'itemDescription' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'estimatedCost' : IDL.Float64,
  'referenceImageHash' : IDL.Opt(IDL.Text),
});
export const SettingsDTO = IDL.Record({
  'gstNumber' : IDL.Text,
  'address' : IDL.Text,
  'defaultLanguage' : IDL.Text,
  'shopName' : IDL.Text,
  'phone' : IDL.Text,
});
export const CustomOrderUpdateDTO = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'delivered' : IDL.Null,
    'inProgress' : IDL.Null,
    'received' : IDL.Null,
    'ready' : IDL.Null,
  }),
  'designNotes' : IDL.Text,
});
export const InvoiceUpdateDTO = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'paid' : IDL.Null,
    'locked' : IDL.Null,
    'draft' : IDL.Null,
    'partial' : IDL.Null,
  }),
});
export const JobOrderUpdateDTO = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'notes' : IDL.Text,
});
export const RepairOrderUpdateDTO = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'delivered' : IDL.Null,
    'inProgress' : IDL.Null,
    'received' : IDL.Null,
    'ready' : IDL.Null,
  }),
  'notes' : IDL.Text,
});

export const GoldRatesDTO = IDL.Record({
  'gold24k' : IDL.Float64,
  'gold22k' : IDL.Float64,
  'gold18k' : IDL.Float64,
  'silver' : IDL.Float64,
});
export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([CustomerDTO], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomOrder' : IDL.Func([CustomOrderDTO], [IDL.Text], []),
  'createInvoice' : IDL.Func([InvoiceDTO], [IDL.Text], []),
  'createJobOrder' : IDL.Func([JobOrderDTO], [IDL.Text], []),
  'createRepairOrder' : IDL.Func([RepairOrderDTO], [IDL.Text], []),
  'createUser' : IDL.Func([UserDTO], [], []),
    'createUserWithCreds' : IDL.Func([IDL.Text, IDL.Text, UserDTO], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomOrder' : IDL.Func([IDL.Text], [IDL.Opt(CustomOrder)], ['query']),
  'getCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrder)], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(CustomerDTO)], ['query']),
  'getGoldRate' : IDL.Func([], [GoldRateDTO], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
  'getInvoiceCounts' : IDL.Func(
      [],
      [IDL.Record({ 'total' : IDL.Nat, 'paid' : IDL.Nat, 'unpaid' : IDL.Nat })],
      ['query'],
    ),
  'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getInvoicesByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Invoice)], ['query']),
  'getJobOrder' : IDL.Func([IDL.Text], [IDL.Opt(JobOrder)], ['query']),
  'getJobOrders' : IDL.Func([], [IDL.Vec(JobOrder)], ['query']),
  'getPaidInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getPaymentHistory' : IDL.Func([IDL.Text], [IDL.Vec(Invoice)], ['query']),
  'getRepairOrder' : IDL.Func([IDL.Text], [IDL.Opt(RepairOrder)], ['query']),
  'getRepairOrders' : IDL.Func([], [IDL.Vec(RepairOrder)], ['query']),
  'getSettings' : IDL.Func([], [SettingsDTO], ['query']),
  'getTotalSales' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalUdharPending' : IDL.Func([], [IDL.Float64], ['query']),
  'getUdharLedger' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getUnpaidInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'lockInvoice' : IDL.Func([IDL.Text], [], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [UserDTO], []),
  'receivePayment' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomOrder' : IDL.Func([CustomOrderUpdateDTO], [], []),
  'updateGoldRate' : IDL.Func([GoldRateDTO], [], []),
  'updateInvoiceStatus' : IDL.Func([InvoiceUpdateDTO], [], []),
  'updateJobOrder' : IDL.Func([JobOrderUpdateDTO], [], []),
  'updateRepairOrder' : IDL.Func([RepairOrderUpdateDTO], [], []),
    'addCustomerWithCreds' : IDL.Func([IDL.Text, IDL.Text, CustomerDTO], [IDL.Text], []),
  'getGoldRates' : IDL.Func([], [GoldRatesDTO], ['query']),
  'getGoldRatesPublic' : IDL.Func([], [GoldRatesDTO], ['query']),
  'updateGoldRates' : IDL.Func([GoldRatesDTO], [], []),
  'updateGoldRatesWithCreds' : IDL.Func([IDL.Text, IDL.Text, GoldRatesDTO], [], []),
'updateSettings' : IDL.Func([SettingsDTO], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CustomerDTO = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomOrderDTO = IDL.Record({
    'customerName' : IDL.Text,
    'itemDescription' : IDL.Text,
    'designNotes' : IDL.Text,
    'dueDate' : Time,
    'advancePaid' : IDL.Float64,
    'phone' : IDL.Text,
    'estimatedCost' : IDL.Float64,
    'referenceImageHash' : IDL.Opt(IDL.Text),
  });
  const InvoiceItem = IDL.Record({
    'weight' : IDL.Float64,
    'total' : IDL.Float64,
    'rate' : IDL.Float64,
    'description' : IDL.Text,
    'purity' : IDL.Float64,
  });
  const InvoiceDTO = IDL.Record({
    'gst' : IDL.Bool,
    'gstPercent' : IDL.Float64,
    'language' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : IDL.Text,
    'items' : IDL.Vec(InvoiceItem),
    'partialPayment' : IDL.Float64,
  });
  const JobOrderDTO = IDL.Record({
    'customerName' : IDL.Text,
    'assignedKaragir' : IDL.Text,
    'dueDate' : Time,
    'description' : IDL.Text,
  });
  const RepairOrderDTO = IDL.Record({
    'customerName' : IDL.Text,
    'itemDescription' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'estimatedCost' : IDL.Float64,
    'referenceImageHash' : IDL.Opt(IDL.Text),
  });
  const Role = IDL.Variant({
    'karagir' : IDL.Null,
    'manager' : IDL.Null,
    'owner' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserDTO = IDL.Record({
    'password' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'phone' : IDL.Text,
  });
  const CustomOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Variant({
      'delivered' : IDL.Null,
      'inProgress' : IDL.Null,
      'received' : IDL.Null,
      'ready' : IDL.Null,
    }),
    'itemDescription' : IDL.Text,
    'createdAt' : Time,
    'designNotes' : IDL.Text,
    'dueDate' : Time,
    'updatedAt' : Time,
    'advancePaid' : IDL.Float64,
    'phone' : IDL.Text,
    'estimatedCost' : IDL.Float64,
    'referenceImageHash' : IDL.Opt(IDL.Text),
  });
  const Customer = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GoldRateDTO = IDL.Record({ 'ratePerGram' : IDL.Float64 });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'gst' : IDL.Bool,
    'status' : IDL.Variant({
      'paid' : IDL.Null,
      'locked' : IDL.Null,
      'draft' : IDL.Null,
      'partial' : IDL.Null,
    }),
    'createdAt' : Time,
    'gstPercent' : IDL.Float64,
    'amountPaid' : IDL.Float64,
    'language' : IDL.Text,
    'updatedAt' : Time,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'udhar' : IDL.Float64,
    'customerId' : IDL.Text,
    'items' : IDL.Vec(InvoiceItem),
    'partialPayment' : IDL.Float64,
  });
  const JobOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'assignedKaragir' : IDL.Text,
    'createdAt' : Time,
    'dueDate' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'notes' : IDL.Text,
  });
  const RepairOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Variant({
      'delivered' : IDL.Null,
      'inProgress' : IDL.Null,
      'received' : IDL.Null,
      'ready' : IDL.Null,
    }),
    'itemDescription' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'estimatedCost' : IDL.Float64,
    'referenceImageHash' : IDL.Opt(IDL.Text),
  });
  const SettingsDTO = IDL.Record({
    'gstNumber' : IDL.Text,
    'address' : IDL.Text,
    'defaultLanguage' : IDL.Text,
    'shopName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CustomOrderUpdateDTO = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'delivered' : IDL.Null,
      'inProgress' : IDL.Null,
      'received' : IDL.Null,
      'ready' : IDL.Null,
    }),
    'designNotes' : IDL.Text,
  });
  const InvoiceUpdateDTO = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'paid' : IDL.Null,
      'locked' : IDL.Null,
      'draft' : IDL.Null,
      'partial' : IDL.Null,
    }),
  });
  const JobOrderUpdateDTO = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'notes' : IDL.Text,
  });
  const RepairOrderUpdateDTO = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'delivered' : IDL.Null,
      'inProgress' : IDL.Null,
      'received' : IDL.Null,
      'ready' : IDL.Null,
    }),
    'notes' : IDL.Text,
  });
  
  const GoldRatesDTO = IDL.Record({
    'gold24k' : IDL.Float64,
    'gold22k' : IDL.Float64,
    'gold18k' : IDL.Float64,
    'silver' : IDL.Float64,
  });
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([CustomerDTO], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomOrder' : IDL.Func([CustomOrderDTO], [IDL.Text], []),
    'createInvoice' : IDL.Func([InvoiceDTO], [IDL.Text], []),
    'createJobOrder' : IDL.Func([JobOrderDTO], [IDL.Text], []),
    'createRepairOrder' : IDL.Func([RepairOrderDTO], [IDL.Text], []),
    'createUser' : IDL.Func([UserDTO], [], []),
    'createUserWithCreds' : IDL.Func([IDL.Text, IDL.Text, UserDTO], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomOrder' : IDL.Func([IDL.Text], [IDL.Opt(CustomOrder)], ['query']),
    'getCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrder)], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(CustomerDTO)], ['query']),
    'getGoldRate' : IDL.Func([], [GoldRateDTO], ['query']),
    'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
    'getInvoiceCounts' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'paid' : IDL.Nat,
            'unpaid' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getInvoicesByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getJobOrder' : IDL.Func([IDL.Text], [IDL.Opt(JobOrder)], ['query']),
    'getJobOrders' : IDL.Func([], [IDL.Vec(JobOrder)], ['query']),
    'getPaidInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getPaymentHistory' : IDL.Func([IDL.Text], [IDL.Vec(Invoice)], ['query']),
    'getRepairOrder' : IDL.Func([IDL.Text], [IDL.Opt(RepairOrder)], ['query']),
    'getRepairOrders' : IDL.Func([], [IDL.Vec(RepairOrder)], ['query']),
    'getSettings' : IDL.Func([], [SettingsDTO], ['query']),
    'getTotalSales' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalUdharPending' : IDL.Func([], [IDL.Float64], ['query']),
    'getUdharLedger' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getUnpaidInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'lockInvoice' : IDL.Func([IDL.Text], [], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [UserDTO], []),
    'receivePayment' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomOrder' : IDL.Func([CustomOrderUpdateDTO], [], []),
    'updateGoldRate' : IDL.Func([GoldRateDTO], [], []),
    'updateInvoiceStatus' : IDL.Func([InvoiceUpdateDTO], [], []),
    'updateJobOrder' : IDL.Func([JobOrderUpdateDTO], [], []),
    'updateRepairOrder' : IDL.Func([RepairOrderUpdateDTO], [], []),
    'addCustomerWithCreds' : IDL.Func([IDL.Text, IDL.Text, CustomerDTO], [IDL.Text], []),
    'getGoldRates' : IDL.Func([], [GoldRatesDTO], ['query']),
    'getGoldRatesPublic' : IDL.Func([], [GoldRatesDTO], ['query']),
    'updateGoldRates' : IDL.Func([GoldRatesDTO], [], []),
    'updateGoldRatesWithCreds' : IDL.Func([IDL.Text, IDL.Text, GoldRatesDTO], [], []),
    'updateSettings' : IDL.Func([SettingsDTO], [], []),
  });
};

export const init = ({ IDL }) => { return []; };