/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomOrder {
  'id' : string,
  'customerName' : string,
  'status' : { 'delivered' : null } |
    { 'inProgress' : null } |
    { 'received' : null } |
    { 'ready' : null },
  'itemDescription' : string,
  'createdAt' : Time,
  'designNotes' : string,
  'dueDate' : Time,
  'updatedAt' : Time,
  'advancePaid' : number,
  'phone' : string,
  'estimatedCost' : number,
  'referenceImageHash' : [] | [string],
}
export interface CustomOrderDTO {
  'customerName' : string,
  'itemDescription' : string,
  'designNotes' : string,
  'dueDate' : Time,
  'advancePaid' : number,
  'phone' : string,
  'estimatedCost' : number,
  'referenceImageHash' : [] | [string],
}
export interface CustomOrderUpdateDTO {
  'id' : string,
  'status' : { 'delivered' : null } |
    { 'inProgress' : null } |
    { 'received' : null } |
    { 'ready' : null },
  'designNotes' : string,
}
export interface Customer {
  'name' : string,
  'createdAt' : Time,
  'address' : string,
  'phone' : string,
}
export interface CustomerDTO {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface GoldRateDTO { 'ratePerGram' : number }
export interface Invoice {
  'id' : string,
  'gst' : boolean,
  'status' : { 'paid' : null } |
    { 'locked' : null } |
    { 'draft' : null } |
    { 'partial' : null },
  'createdAt' : Time,
  'gstPercent' : number,
  'amountPaid' : number,
  'language' : string,
  'updatedAt' : Time,
  'totalAmount' : number,
  'notes' : string,
  'udhar' : number,
  'customerId' : string,
  'items' : Array<InvoiceItem>,
  'partialPayment' : number,
}
export interface InvoiceDTO {
  'gst' : boolean,
  'gstPercent' : number,
  'language' : string,
  'notes' : string,
  'customerId' : string,
  'items' : Array<InvoiceItem>,
  'partialPayment' : number,
}
export interface InvoiceItem {
  'weight' : number,
  'total' : number,
  'rate' : number,
  'description' : string,
  'purity' : number,
}
export interface InvoiceUpdateDTO {
  'id' : string,
  'status' : { 'paid' : null } |
    { 'locked' : null } |
    { 'draft' : null } |
    { 'partial' : null },
}
export interface JobOrder {
  'id' : string,
  'customerName' : string,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'inProgress' : null },
  'assignedKaragir' : string,
  'createdAt' : Time,
  'dueDate' : Time,
  'description' : string,
  'updatedAt' : Time,
  'notes' : string,
}
export interface JobOrderDTO {
  'customerName' : string,
  'assignedKaragir' : string,
  'dueDate' : Time,
  'description' : string,
}
export interface JobOrderUpdateDTO {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'inProgress' : null },
  'notes' : string,
}
export interface RepairOrder {
  'id' : string,
  'customerName' : string,
  'status' : { 'delivered' : null } |
    { 'inProgress' : null } |
    { 'received' : null } |
    { 'ready' : null },
  'itemDescription' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'notes' : string,
  'phone' : string,
  'estimatedCost' : number,
  'referenceImageHash' : [] | [string],
}
export interface RepairOrderDTO {
  'customerName' : string,
  'itemDescription' : string,
  'notes' : string,
  'phone' : string,
  'estimatedCost' : number,
  'referenceImageHash' : [] | [string],
}
export interface RepairOrderUpdateDTO {
  'id' : string,
  'status' : { 'delivered' : null } |
    { 'inProgress' : null } |
    { 'received' : null } |
    { 'ready' : null },
  'notes' : string,
}
export type Role = { 'karagir' : null } |
  { 'manager' : null } |
  { 'owner' : null } |
  { 'staff' : null };
export interface SettingsDTO {
  'gstNumber' : string,
  'address' : string,
  'defaultLanguage' : string,
  'shopName' : string,
  'phone' : string,
}
export type Time = bigint;
export interface UserDTO {
  'password' : string,
  'name' : string,
  'role' : Role,
  'phone' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : Role,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[CustomerDTO], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomOrder' : ActorMethod<[CustomOrderDTO], string>,
  'createInvoice' : ActorMethod<[InvoiceDTO], string>,
  'createJobOrder' : ActorMethod<[JobOrderDTO], string>,
  'createRepairOrder' : ActorMethod<[RepairOrderDTO], string>,
  'createUser' : ActorMethod<[UserDTO], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomOrder' : ActorMethod<[string], [] | [CustomOrder]>,
  'getCustomOrders' : ActorMethod<[], Array<CustomOrder>>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getCustomers' : ActorMethod<[], Array<CustomerDTO>>,
  'getGoldRate' : ActorMethod<[], GoldRateDTO>,
  'getInvoice' : ActorMethod<[string], [] | [Invoice]>,
  'getInvoiceCounts' : ActorMethod<
    [],
    { 'total' : bigint, 'paid' : bigint, 'unpaid' : bigint }
  >,
  'getInvoices' : ActorMethod<[], Array<Invoice>>,
  'getInvoicesByCustomer' : ActorMethod<[string], Array<Invoice>>,
  'getJobOrder' : ActorMethod<[string], [] | [JobOrder]>,
  'getJobOrders' : ActorMethod<[], Array<JobOrder>>,
  'getPaidInvoices' : ActorMethod<[], Array<Invoice>>,
  'getPaymentHistory' : ActorMethod<[string], Array<Invoice>>,
  'getRepairOrder' : ActorMethod<[string], [] | [RepairOrder]>,
  'getRepairOrders' : ActorMethod<[], Array<RepairOrder>>,
  'getSettings' : ActorMethod<[], SettingsDTO>,
  'getTotalSales' : ActorMethod<[], number>,
  'getTotalUdharPending' : ActorMethod<[], number>,
  'getUdharLedger' : ActorMethod<[], Array<Invoice>>,
  'getUnpaidInvoices' : ActorMethod<[], Array<Invoice>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lockInvoice' : ActorMethod<[string], undefined>,
  'login' : ActorMethod<[string, string], UserDTO>,
  'receivePayment' : ActorMethod<[string, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomOrder' : ActorMethod<[CustomOrderUpdateDTO], undefined>,
  'updateGoldRate' : ActorMethod<[GoldRateDTO], undefined>,
  'updateInvoiceStatus' : ActorMethod<[InvoiceUpdateDTO], undefined>,
  'updateJobOrder' : ActorMethod<[JobOrderUpdateDTO], undefined>,
  'updateRepairOrder' : ActorMethod<[RepairOrderUpdateDTO], undefined>,
  'addCustomerWithCreds' : ActorMethod<[string, string, CustomerDTO], string>,
  'getGoldRates' : ActorMethod<[], { gold24k: number, gold22k: number, gold18k: number, silver: number }>,
  'getGoldRatesPublic' : ActorMethod<[], { gold24k: number, gold22k: number, gold18k: number, silver: number }>,
  'updateGoldRates' : ActorMethod<[{ gold24k: number, gold22k: number, gold18k: number, silver: number }], undefined>,
  'updateGoldRatesWithCreds' : ActorMethod<[string, string, { gold24k: number, gold22k: number, gold18k: number, silver: number }], undefined>,
  'updateSettings' : ActorMethod<[SettingsDTO], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];