/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SettingsDTO {
    gstNumber: string;
    address: string;
    defaultLanguage: string;
    shopName: string;
    phone: string;
}
export interface RepairOrder {
    id: string;
    customerName: string;
    status: Variant_delivered_inProgress_received_ready;
    itemDescription: string;
    createdAt: Time;
    updatedAt: Time;
    notes: string;
    phone: string;
    estimatedCost: number;
    referenceImageHash?: string;
}
export interface InvoiceItem {
    weight: number;
    total: number;
    rate: number;
    description: string;
    purity: number;
}
export type Time = bigint;
export interface JobOrderUpdateDTO {
    id: string;
    status: Variant_pending_completed_inProgress;
    notes: string;
}
export interface InvoiceDTO {
    gst: boolean;
    gstPercent: number;
    language: string;
    notes: string;
    customerId: string;
    items: Array<InvoiceItem>;
    partialPayment: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CustomOrderDTO {
    customerName: string;
    itemDescription: string;
    designNotes: string;
    dueDate: Time;
    advancePaid: number;
    phone: string;
    estimatedCost: number;
    referenceImageHash?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Invoice {
    id: string;
    gst: boolean;
    status: Variant_paid_locked_draft_partial;
    createdAt: Time;
    gstPercent: number;
    amountPaid: number;
    language: string;
    updatedAt: Time;
    totalAmount: number;
    notes: string;
    udhar: number;
    customerId: string;
    items: Array<InvoiceItem>;
    partialPayment: number;
}
export interface JobOrder {
    id: string;
    customerName: string;
    status: Variant_pending_completed_inProgress;
    assignedKaragir: string;
    createdAt: Time;
    dueDate: Time;
    description: string;
    updatedAt: Time;
    notes: string;
}
export interface Customer {
    name: string;
    createdAt: Time;
    address: string;
    phone: string;
}
export interface InvoiceUpdateDTO {
    id: string;
    status: Variant_paid_locked_draft_partial;
}
export interface JobOrderDTO {
    customerName: string;
    assignedKaragir: string;
    dueDate: Time;
    description: string;
}
export interface CustomOrderUpdateDTO {
    id: string;
    status: Variant_delivered_inProgress_received_ready;
    designNotes: string;
}
export interface RepairOrderDTO {
    customerName: string;
    itemDescription: string;
    notes: string;
    phone: string;
    estimatedCost: number;
    referenceImageHash?: string;
}
export interface UserDTO {
    password: string;
    name: string;
    role: Role;
    phone: string;
}
export interface GoldRateDTO {
    ratePerGram: number;
}
export interface GoldRatesDTO {
    gold24k: number;
    gold22k: number;
    gold18k: number;
    silver: number;
}
export interface RepairOrderUpdateDTO {
    id: string;
    status: Variant_delivered_inProgress_received_ready;
    notes: string;
}
export interface CustomerDTO {
    name: string;
    address: string;
    phone: string;
}
export interface CustomOrder {
    id: string;
    customerName: string;
    status: Variant_delivered_inProgress_received_ready;
    itemDescription: string;
    createdAt: Time;
    designNotes: string;
    dueDate: Time;
    updatedAt: Time;
    advancePaid: number;
    phone: string;
    estimatedCost: number;
    referenceImageHash?: string;
}
export interface UserProfile {
    name: string;
    role: Role;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Role {
    karagir = "karagir",
    manager = "manager",
    owner = "owner",
    staff = "staff"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_delivered_inProgress_received_ready {
    delivered = "delivered",
    inProgress = "inProgress",
    received = "received",
    ready = "ready"
}
export enum Variant_paid_locked_draft_partial {
    paid = "paid",
    locked = "locked",
    draft = "draft",
    partial = "partial"
}
export enum Variant_pending_completed_inProgress {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomer(customer: CustomerDTO): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCustomOrder(customOrder: CustomOrderDTO): Promise<string>;
    createInvoice(invoice: InvoiceDTO): Promise<string>;
    createJobOrder(job: JobOrderDTO): Promise<string>;
    createRepairOrder(repairOrder: RepairOrderDTO): Promise<string>;
    createUser(userDTO: UserDTO): Promise<void>;
    createUserWithCreds(callerPhone: string, callerPassword: string, userDTO: UserDTO): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomOrder(id: string): Promise<CustomOrder | null>;
    getCustomOrders(): Promise<Array<CustomOrder>>;
    getCustomer(phone: string): Promise<Customer | null>;
    getCustomers(): Promise<Array<CustomerDTO>>;
    getGoldRate(): Promise<GoldRateDTO>;
    getGoldRates(): Promise<GoldRatesDTO>;
    getInvoice(id: string): Promise<Invoice | null>;
    getInvoiceCounts(): Promise<{
        total: bigint;
        paid: bigint;
        unpaid: bigint;
    }>;
    getInvoices(): Promise<Array<Invoice>>;
    getInvoicesByCustomer(customerId: string): Promise<Array<Invoice>>;
    getJobOrder(id: string): Promise<JobOrder | null>;
    getJobOrders(): Promise<Array<JobOrder>>;
    getPaidInvoices(): Promise<Array<Invoice>>;
    getPaymentHistory(customerId: string): Promise<Array<Invoice>>;
    getRepairOrder(id: string): Promise<RepairOrder | null>;
    getRepairOrders(): Promise<Array<RepairOrder>>;
    getSettings(): Promise<SettingsDTO>;
    getTotalSales(): Promise<number>;
    getTotalUdharPending(): Promise<number>;
    getUdharLedger(): Promise<Array<Invoice>>;
    getUnpaidInvoices(): Promise<Array<Invoice>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    lockInvoice(id: string): Promise<void>;
    login(phone: string, password: string): Promise<UserDTO>;
    receivePayment(invoiceId: string, amount: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCustomOrder(update: CustomOrderUpdateDTO): Promise<void>;
    updateGoldRate(newRate: GoldRateDTO): Promise<void>;
    addCustomerWithCreds(phone: string, password: string, customer: CustomerDTO): Promise<string>;
    updateGoldRatesWithCreds(phone: string, password: string, newRates: GoldRatesDTO): Promise<void>;
    getGoldRatesPublic(): Promise<GoldRatesDTO>;
    loginWithCreds(phone: string, password: string): Promise<UserDTO>;
    getCustomersWithCreds(phone: string, password: string): Promise<CustomerDTO[]>;
    getCustomerWithCreds(callerPhone: string, password: string, customerPhone: string): Promise<Customer | null>;
    getUserProfileWithCreds(phone: string, password: string): Promise<UserProfile>;
    createUserWithCreds(callerPhone: string, callerPassword: string, userDTO: UserDTO): Promise<void>;
    createInvoiceWithCreds(phone: string, password: string, invoice: InvoiceDTO): Promise<string>;
    lockInvoiceWithCreds(phone: string, password: string, id: string): Promise<void>;
    updateInvoiceStatusWithCreds(phone: string, password: string, update: InvoiceUpdateDTO): Promise<void>;
    getInvoicesWithCreds(phone: string, password: string): Promise<Invoice[]>;
    getInvoicesByCustomerWithCreds(phone: string, password: string, customerId: string): Promise<Invoice[]>;
    receivePaymentWithCreds(phone: string, password: string, invoiceId: string, amount: number): Promise<void>;
    addManualUdharWithCreds(callerPhone: string, password: string, customerPhone: string, amount: number, notes: string): Promise<string>;
    getUdharLedgerWithCreds(phone: string, password: string): Promise<Invoice[]>;
    getPaymentHistoryWithCreds(callerPhone: string, password: string, customerId: string): Promise<Invoice[]>;
    getTotalSalesWithCreds(phone: string, password: string): Promise<number>;
    getTotalUdharPendingWithCreds(phone: string, password: string): Promise<number>;
    getInvoiceCountsWithCreds(phone: string, password: string): Promise<{total: bigint, paid: bigint, unpaid: bigint}>;
    createJobOrderWithCreds(phone: string, password: string, job: JobOrderDTO): Promise<string>;
    updateJobOrderWithCreds(phone: string, password: string, update: JobOrderUpdateDTO): Promise<void>;
    getJobOrdersWithCreds(phone: string, password: string): Promise<JobOrder[]>;
    createRepairOrderWithCreds(phone: string, password: string, repairOrder: RepairOrderDTO): Promise<string>;
    updateRepairOrderWithCreds(phone: string, password: string, update: RepairOrderUpdateDTO): Promise<void>;
    getRepairOrdersWithCreds(phone: string, password: string): Promise<RepairOrder[]>;
    createCustomOrderWithCreds(phone: string, password: string, customOrder: CustomOrderDTO): Promise<string>;
    updateCustomOrderWithCreds(phone: string, password: string, update: CustomOrderUpdateDTO): Promise<void>;
    getCustomOrdersWithCreds(phone: string, password: string): Promise<CustomOrder[]>;
    updateSettingsWithCreds(phone: string, password: string, newSettings: SettingsDTO): Promise<void>;
    getSettingsPublic(): Promise<SettingsDTO>;
    updateGoldRates(newRates: GoldRatesDTO): Promise<void>;
    updateInvoiceStatus(update: InvoiceUpdateDTO): Promise<void>;
    updateJobOrder(update: JobOrderUpdateDTO): Promise<void>;
    updateRepairOrder(update: RepairOrderUpdateDTO): Promise<void>;
    updateSettings(newSettings: SettingsDTO): Promise<void>;
}
import type { CustomOrder as _CustomOrder, CustomOrderDTO as _CustomOrderDTO, CustomOrderUpdateDTO as _CustomOrderUpdateDTO, Customer as _Customer, Invoice as _Invoice, InvoiceItem as _InvoiceItem, InvoiceUpdateDTO as _InvoiceUpdateDTO, JobOrder as _JobOrder, JobOrderUpdateDTO as _JobOrderUpdateDTO, RepairOrder as _RepairOrder, RepairOrderDTO as _RepairOrderDTO, RepairOrderUpdateDTO as _RepairOrderUpdateDTO, Role as _Role, Time as _Time, UserDTO as _UserDTO, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomer(arg0: CustomerDTO): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomOrder(arg0: CustomOrderDTO): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomOrder(to_candid_CustomOrderDTO_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomOrder(to_candid_CustomOrderDTO_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createInvoice(arg0: InvoiceDTO): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0);
            return result;
        }
    }
    async createJobOrder(arg0: JobOrderDTO): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobOrder(arg0);
            return result;
        }
    }
    async createRepairOrder(arg0: RepairOrderDTO): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createRepairOrder(to_candid_RepairOrderDTO_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRepairOrder(to_candid_RepairOrderDTO_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createUser(arg0: UserDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(to_candid_UserDTO_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(to_candid_UserDTO_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createUserWithCreds(arg0: string, arg1: string, arg2: UserDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserWithCreds(arg0, arg1, to_candid_UserDTO_n14(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserWithCreds(arg0, arg1, to_candid_UserDTO_n14(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomOrder(arg0: string): Promise<CustomOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomOrder(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomOrder(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomOrders(): Promise<Array<CustomOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomOrders();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomOrders();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: string): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<CustomerDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getGoldRate(): Promise<GoldRateDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoldRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoldRate();
            return result;
        }
    }
    async getGoldRates(): Promise<GoldRatesDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoldRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoldRates();
            return result;
        }
    }
    async getInvoice(arg0: string): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoiceCounts(): Promise<{
        total: bigint;
        paid: bigint;
        unpaid: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceCounts();
            return result;
        }
    }
    async getInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoices();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoices();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByCustomer(arg0: string): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByCustomer(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByCustomer(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobOrder(arg0: string): Promise<JobOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobOrder(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobOrder(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobOrders(): Promise<Array<JobOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobOrders();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobOrders();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaidInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaidInvoices();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaidInvoices();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentHistory(arg0: string): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentHistory(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentHistory(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepairOrder(arg0: string): Promise<RepairOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepairOrder(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepairOrder(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepairOrders(): Promise<Array<RepairOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepairOrders();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepairOrders();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<SettingsDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getTotalSales(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSales();
            return result;
        }
    }
    async getTotalUdharPending(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalUdharPending();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalUdharPending();
            return result;
        }
    }
    async getUdharLedger(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUdharLedger();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUdharLedger();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnpaidInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnpaidInvoices();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnpaidInvoices();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async lockInvoice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.lockInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockInvoice(arg0);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<UserDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_UserDTO_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_UserDTO_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async receivePayment(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.receivePayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.receivePayment(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCustomOrder(arg0: CustomOrderUpdateDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomOrder(to_candid_CustomOrderUpdateDTO_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomOrder(to_candid_CustomOrderUpdateDTO_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateGoldRate(arg0: GoldRateDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoldRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoldRate(arg0);
            return result;
        }
    }
    async updateGoldRates(arg0: GoldRatesDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoldRates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoldRates(arg0);
            return result;
        }
    }

    async addCustomerWithCreds(arg0: string, arg1: string, arg2: CustomerDTO): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomerWithCreds(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error('unreachable');
            }
        } else {
            const result = await this.actor.addCustomerWithCreds(arg0, arg1, arg2);
            return result;
        }
    }
    async updateGoldRatesWithCreds(arg0: string, arg1: string, arg2: GoldRatesDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoldRatesWithCreds(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error('unreachable');
            }
        } else {
            const result = await this.actor.updateGoldRatesWithCreds(arg0, arg1, arg2);
            return result;
        }
    }
    async getGoldRatesPublic(): Promise<GoldRatesDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoldRatesPublic();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error('unreachable');
            }
        } else {
            const result = await this.actor.getGoldRatesPublic();
            return result;
        }
    }

    async updateInvoiceStatus(arg0: InvoiceUpdateDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoiceStatus(to_candid_InvoiceUpdateDTO_n53(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoiceStatus(to_candid_InvoiceUpdateDTO_n53(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJobOrder(arg0: JobOrderUpdateDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobOrder(to_candid_JobOrderUpdateDTO_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobOrder(to_candid_JobOrderUpdateDTO_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRepairOrder(arg0: RepairOrderUpdateDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRepairOrder(to_candid_RepairOrderUpdateDTO_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRepairOrder(to_candid_RepairOrderUpdateDTO_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSettings(arg0: SettingsDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async loginWithCreds(arg0: string, arg1: string): Promise<UserDTO> {
        const result = await this.actor.loginWithCreds(arg0, arg1);
        return result as unknown as UserDTO;
    }
    async getCustomersWithCreds(arg0: string, arg1: string): Promise<CustomerDTO[]> {
        const result = await this.actor.getCustomersWithCreds(arg0, arg1);
        return result as unknown as CustomerDTO[];
    }
    async getCustomerWithCreds(arg0: string, arg1: string, arg2: string): Promise<Customer | null> {
        const result = await this.actor.getCustomerWithCreds(arg0, arg1, arg2);
        return (result as [Customer] | [])[0] ?? null;
    }
    async getUserProfileWithCreds(arg0: string, arg1: string): Promise<UserProfile> {
        const result = await this.actor.getUserProfileWithCreds(arg0, arg1);
        return result as unknown as UserProfile;
    }
    async createInvoiceWithCreds(arg0: string, arg1: string, arg2: InvoiceDTO): Promise<string> {
        const result = await this.actor.createInvoiceWithCreds(arg0, arg1, arg2);
        return result;
    }
    async lockInvoiceWithCreds(arg0: string, arg1: string, arg2: string): Promise<void> {
        return this.actor.lockInvoiceWithCreds(arg0, arg1, arg2);
    }
    async updateInvoiceStatusWithCreds(arg0: string, arg1: string, arg2: InvoiceUpdateDTO): Promise<void> {
        const candidArg2 = { id: arg2.id, status: arg2.status === 'paid' ? {paid:null} : arg2.status === 'locked' ? {locked:null} : arg2.status === 'partial' ? {partial:null} : {draft:null} };
        return this.actor.updateInvoiceStatusWithCreds(arg0, arg1, candidArg2 as any);
    }
    async getInvoicesWithCreds(arg0: string, arg1: string): Promise<Invoice[]> {
        const result = await this.actor.getInvoicesWithCreds(arg0, arg1);
        return from_candid_vec_n36(this._uploadFile, this._downloadFile, result as any);
    }
    async getInvoicesByCustomerWithCreds(arg0: string, arg1: string, arg2: string): Promise<Invoice[]> {
        const result = await this.actor.getInvoicesByCustomerWithCreds(arg0, arg1, arg2);
        return from_candid_vec_n36(this._uploadFile, this._downloadFile, result as any);
    }
    async receivePaymentWithCreds(arg0: string, arg1: string, arg2: string, arg3: number): Promise<void> {
        return this.actor.receivePaymentWithCreds(arg0, arg1, arg2, arg3);
    }
    async addManualUdharWithCreds(arg0: string, arg1: string, arg2: string, arg3: number, arg4: string): Promise<string> {
        return this.actor.addManualUdharWithCreds(arg0, arg1, arg2, arg3, arg4);
    }
    async getUdharLedgerWithCreds(arg0: string, arg1: string): Promise<Invoice[]> {
        const result = await this.actor.getUdharLedgerWithCreds(arg0, arg1);
        return from_candid_vec_n36(this._uploadFile, this._downloadFile, result as any);
    }
    async getPaymentHistoryWithCreds(arg0: string, arg1: string, arg2: string): Promise<Invoice[]> {
        const result = await this.actor.getPaymentHistoryWithCreds(arg0, arg1, arg2);
        return from_candid_vec_n36(this._uploadFile, this._downloadFile, result as any);
    }
    async getTotalSalesWithCreds(arg0: string, arg1: string): Promise<number> {
        return this.actor.getTotalSalesWithCreds(arg0, arg1);
    }
    async getTotalUdharPendingWithCreds(arg0: string, arg1: string): Promise<number> {
        return this.actor.getTotalUdharPendingWithCreds(arg0, arg1);
    }
    async getInvoiceCountsWithCreds(arg0: string, arg1: string): Promise<{total: bigint, paid: bigint, unpaid: bigint}> {
        const result = await this.actor.getInvoiceCountsWithCreds(arg0, arg1);
        return result as unknown as {total: bigint, paid: bigint, unpaid: bigint};
    }
    async createJobOrderWithCreds(arg0: string, arg1: string, arg2: JobOrderDTO): Promise<string> {
        const candidArg2 = { customerName: arg2.customerName, description: arg2.description, assignedKaragir: arg2.assignedKaragir, dueDate: arg2.dueDate };
        return this.actor.createJobOrderWithCreds(arg0, arg1, candidArg2 as any);
    }
    async updateJobOrderWithCreds(arg0: string, arg1: string, arg2: JobOrderUpdateDTO): Promise<void> {
        const candidArg2 = { id: arg2.id, notes: arg2.notes, status: arg2.status === 'pending' ? {pending:null} : arg2.status === 'completed' ? {completed:null} : {inProgress:null} };
        return this.actor.updateJobOrderWithCreds(arg0, arg1, candidArg2 as any);
    }
    async getJobOrdersWithCreds(arg0: string, arg1: string): Promise<JobOrder[]> {
        const result = await this.actor.getJobOrdersWithCreds(arg0, arg1);
        return from_candid_vec_n41(this._uploadFile, this._downloadFile, result as any);
    }
    async createRepairOrderWithCreds(arg0: string, arg1: string, arg2: RepairOrderDTO): Promise<string> {
        const candidArg2 = { ...arg2, referenceImageHash: arg2.referenceImageHash ? [arg2.referenceImageHash] : [] };
        return this.actor.createRepairOrderWithCreds(arg0, arg1, candidArg2 as any);
    }
    async updateRepairOrderWithCreds(arg0: string, arg1: string, arg2: RepairOrderUpdateDTO): Promise<void> {
        const candidArg2 = { id: arg2.id, notes: arg2.notes, status: arg2.status === 'delivered' ? {delivered:null} : arg2.status === 'ready' ? {ready:null} : arg2.status === 'inProgress' ? {inProgress:null} : {received:null} };
        return this.actor.updateRepairOrderWithCreds(arg0, arg1, candidArg2 as any);
    }
    async getRepairOrdersWithCreds(arg0: string, arg1: string): Promise<RepairOrder[]> {
        const result = await this.actor.getRepairOrdersWithCreds(arg0, arg1);
        return from_candid_vec_n45(this._uploadFile, this._downloadFile, result as any);
    }
    async createCustomOrderWithCreds(arg0: string, arg1: string, arg2: CustomOrderDTO): Promise<string> {
        const candidArg2 = { ...arg2, referenceImageHash: arg2.referenceImageHash ? [arg2.referenceImageHash] : [] };
        return this.actor.createCustomOrderWithCreds(arg0, arg1, candidArg2 as any);
    }
    async updateCustomOrderWithCreds(arg0: string, arg1: string, arg2: CustomOrderUpdateDTO): Promise<void> {
        const candidArg2 = { id: arg2.id, designNotes: arg2.designNotes, status: arg2.status === 'delivered' ? {delivered:null} : arg2.status === 'ready' ? {ready:null} : arg2.status === 'inProgress' ? {inProgress:null} : {received:null} };
        return this.actor.updateCustomOrderWithCreds(arg0, arg1, candidArg2 as any);
    }
    async getCustomOrdersWithCreds(arg0: string, arg1: string): Promise<CustomOrder[]> {
        const result = await this.actor.getCustomOrdersWithCreds(arg0, arg1);
        return from_candid_vec_n30(this._uploadFile, this._downloadFile, result as any);
    }
    async updateSettingsWithCreds(arg0: string, arg1: string, arg2: SettingsDTO): Promise<void> {
        return this.actor.updateSettingsWithCreds(arg0, arg1, arg2);
    }
    async getSettingsPublic(): Promise<SettingsDTO> {
        return this.actor.getSettingsPublic();
    }
}
function from_candid_CustomOrder_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomOrder): CustomOrder {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_JobOrder_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobOrder): JobOrder {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_RepairOrder_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepairOrder): RepairOrder {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserDTO_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserDTO): UserDTO {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomOrder]): CustomOrder | null {
    return value.length === 0 ? null : from_candid_CustomOrder_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobOrder]): JobOrder | null {
    return value.length === 0 ? null : from_candid_JobOrder_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RepairOrder]): RepairOrder | null {
    return value.length === 0 ? null : from_candid_RepairOrder_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _Role;
    phone: string;
}): {
    name: string;
    role: Role;
    phone: string;
} {
    return {
        name: value.name,
        role: from_candid_Role_n21(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: {
        delivered: null;
    } | {
        inProgress: null;
    } | {
        received: null;
    } | {
        ready: null;
    };
    itemDescription: string;
    createdAt: _Time;
    designNotes: string;
    dueDate: _Time;
    updatedAt: _Time;
    advancePaid: number;
    phone: string;
    estimatedCost: number;
    referenceImageHash: [] | [string];
}): {
    id: string;
    customerName: string;
    status: Variant_delivered_inProgress_received_ready;
    itemDescription: string;
    createdAt: Time;
    designNotes: string;
    dueDate: Time;
    updatedAt: Time;
    advancePaid: number;
    phone: string;
    estimatedCost: number;
    referenceImageHash?: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_variant_n28(_uploadFile, _downloadFile, value.status),
        itemDescription: value.itemDescription,
        createdAt: value.createdAt,
        designNotes: value.designNotes,
        dueDate: value.dueDate,
        updatedAt: value.updatedAt,
        advancePaid: value.advancePaid,
        phone: value.phone,
        estimatedCost: value.estimatedCost,
        referenceImageHash: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.referenceImageHash))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    gst: boolean;
    status: {
        paid: null;
    } | {
        locked: null;
    } | {
        draft: null;
    } | {
        partial: null;
    };
    createdAt: _Time;
    gstPercent: number;
    amountPaid: number;
    language: string;
    updatedAt: _Time;
    totalAmount: number;
    notes: string;
    udhar: number;
    customerId: string;
    items: Array<_InvoiceItem>;
    partialPayment: number;
}): {
    id: string;
    gst: boolean;
    status: Variant_paid_locked_draft_partial;
    createdAt: Time;
    gstPercent: number;
    amountPaid: number;
    language: string;
    updatedAt: Time;
    totalAmount: number;
    notes: string;
    udhar: number;
    customerId: string;
    items: Array<InvoiceItem>;
    partialPayment: number;
} {
    return {
        id: value.id,
        gst: value.gst,
        status: from_candid_variant_n35(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        gstPercent: value.gstPercent,
        amountPaid: value.amountPaid,
        language: value.language,
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        notes: value.notes,
        udhar: value.udhar,
        customerId: value.customerId,
        items: value.items,
        partialPayment: value.partialPayment
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        inProgress: null;
    };
    assignedKaragir: string;
    createdAt: _Time;
    dueDate: _Time;
    description: string;
    updatedAt: _Time;
    notes: string;
}): {
    id: string;
    customerName: string;
    status: Variant_pending_completed_inProgress;
    assignedKaragir: string;
    createdAt: Time;
    dueDate: Time;
    description: string;
    updatedAt: Time;
    notes: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_variant_n40(_uploadFile, _downloadFile, value.status),
        assignedKaragir: value.assignedKaragir,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        description: value.description,
        updatedAt: value.updatedAt,
        notes: value.notes
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: {
        delivered: null;
    } | {
        inProgress: null;
    } | {
        received: null;
    } | {
        ready: null;
    };
    itemDescription: string;
    createdAt: _Time;
    updatedAt: _Time;
    notes: string;
    phone: string;
    estimatedCost: number;
    referenceImageHash: [] | [string];
}): {
    id: string;
    customerName: string;
    status: Variant_delivered_inProgress_received_ready;
    itemDescription: string;
    createdAt: Time;
    updatedAt: Time;
    notes: string;
    phone: string;
    estimatedCost: number;
    referenceImageHash?: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_variant_n28(_uploadFile, _downloadFile, value.status),
        itemDescription: value.itemDescription,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        notes: value.notes,
        phone: value.phone,
        estimatedCost: value.estimatedCost,
        referenceImageHash: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.referenceImageHash))
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password: string;
    name: string;
    role: _Role;
    phone: string;
}): {
    password: string;
    name: string;
    role: Role;
    phone: string;
} {
    return {
        password: value.password,
        name: value.name,
        role: from_candid_Role_n21(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    karagir: null;
} | {
    manager: null;
} | {
    owner: null;
} | {
    staff: null;
}): Role {
    return "karagir" in value ? Role.karagir : "manager" in value ? Role.manager : "owner" in value ? Role.owner : "staff" in value ? Role.staff : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    delivered: null;
} | {
    inProgress: null;
} | {
    received: null;
} | {
    ready: null;
}): Variant_delivered_inProgress_received_ready {
    return "delivered" in value ? Variant_delivered_inProgress_received_ready.delivered : "inProgress" in value ? Variant_delivered_inProgress_received_ready.inProgress : "received" in value ? Variant_delivered_inProgress_received_ready.received : "ready" in value ? Variant_delivered_inProgress_received_ready.ready : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    locked: null;
} | {
    draft: null;
} | {
    partial: null;
}): Variant_paid_locked_draft_partial {
    return "paid" in value ? Variant_paid_locked_draft_partial.paid : "locked" in value ? Variant_paid_locked_draft_partial.locked : "draft" in value ? Variant_paid_locked_draft_partial.draft : "partial" in value ? Variant_paid_locked_draft_partial.partial : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): Variant_pending_completed_inProgress {
    return "pending" in value ? Variant_pending_completed_inProgress.pending : "completed" in value ? Variant_pending_completed_inProgress.completed : "inProgress" in value ? Variant_pending_completed_inProgress.inProgress : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomOrder>): Array<CustomOrder> {
    return value.map((x)=>from_candid_CustomOrder_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobOrder>): Array<JobOrder> {
    return value.map((x)=>from_candid_JobOrder_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RepairOrder>): Array<RepairOrder> {
    return value.map((x)=>from_candid_RepairOrder_n43(_uploadFile, _downloadFile, x));
}
function to_candid_CustomOrderDTO_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomOrderDTO): _CustomOrderDTO {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_CustomOrderUpdateDTO_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomOrderUpdateDTO): _CustomOrderUpdateDTO {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceUpdateDTO_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceUpdateDTO): _InvoiceUpdateDTO {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_JobOrderUpdateDTO_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobOrderUpdateDTO): _JobOrderUpdateDTO {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_RepairOrderDTO_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairOrderDTO): _RepairOrderDTO {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_RepairOrderUpdateDTO_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairOrderUpdateDTO): _RepairOrderUpdateDTO {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserDTO_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserDTO): _UserDTO {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    itemDescription: string;
    designNotes: string;
    dueDate: Time;
    advancePaid: number;
    phone: string;
    estimatedCost: number;
    referenceImageHash?: string;
}): {
    customerName: string;
    itemDescription: string;
    designNotes: string;
    dueDate: _Time;
    advancePaid: number;
    phone: string;
    estimatedCost: number;
    referenceImageHash: [] | [string];
} {
    return {
        customerName: value.customerName,
        itemDescription: value.itemDescription,
        designNotes: value.designNotes,
        dueDate: value.dueDate,
        advancePaid: value.advancePaid,
        phone: value.phone,
        estimatedCost: value.estimatedCost,
        referenceImageHash: value.referenceImageHash ? candid_some(value.referenceImageHash) : candid_none()
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    itemDescription: string;
    notes: string;
    phone: string;
    estimatedCost: number;
    referenceImageHash?: string;
}): {
    customerName: string;
    itemDescription: string;
    notes: string;
    phone: string;
    estimatedCost: number;
    referenceImageHash: [] | [string];
} {
    return {
        customerName: value.customerName,
        itemDescription: value.itemDescription,
        notes: value.notes,
        phone: value.phone,
        estimatedCost: value.estimatedCost,
        referenceImageHash: value.referenceImageHash ? candid_some(value.referenceImageHash) : candid_none()
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password: string;
    name: string;
    role: Role;
    phone: string;
}): {
    password: string;
    name: string;
    role: _Role;
    phone: string;
} {
    return {
        password: value.password,
        name: value.name,
        role: to_candid_Role_n16(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
    phone: string;
}): {
    name: string;
    role: _Role;
    phone: string;
} {
    return {
        name: value.name,
        role: to_candid_Role_n16(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_delivered_inProgress_received_ready;
    designNotes: string;
}): {
    id: string;
    status: {
        delivered: null;
    } | {
        inProgress: null;
    } | {
        received: null;
    } | {
        ready: null;
    };
    designNotes: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n52(_uploadFile, _downloadFile, value.status),
        designNotes: value.designNotes
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_paid_locked_draft_partial;
}): {
    id: string;
    status: {
        paid: null;
    } | {
        locked: null;
    } | {
        draft: null;
    } | {
        partial: null;
    };
} {
    return {
        id: value.id,
        status: to_candid_variant_n55(_uploadFile, _downloadFile, value.status)
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_pending_completed_inProgress;
    notes: string;
}): {
    id: string;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        inProgress: null;
    };
    notes: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n58(_uploadFile, _downloadFile, value.status),
        notes: value.notes
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_delivered_inProgress_received_ready;
    notes: string;
}): {
    id: string;
    status: {
        delivered: null;
    } | {
        inProgress: null;
    } | {
        received: null;
    } | {
        ready: null;
    };
    notes: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n52(_uploadFile, _downloadFile, value.status),
        notes: value.notes
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    karagir: null;
} | {
    manager: null;
} | {
    owner: null;
} | {
    staff: null;
} {
    return value == Role.karagir ? {
        karagir: null
    } : value == Role.manager ? {
        manager: null
    } : value == Role.owner ? {
        owner: null
    } : value == Role.staff ? {
        staff: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_delivered_inProgress_received_ready): {
    delivered: null;
} | {
    inProgress: null;
} | {
    received: null;
} | {
    ready: null;
} {
    return value == Variant_delivered_inProgress_received_ready.delivered ? {
        delivered: null
    } : value == Variant_delivered_inProgress_received_ready.inProgress ? {
        inProgress: null
    } : value == Variant_delivered_inProgress_received_ready.received ? {
        received: null
    } : value == Variant_delivered_inProgress_received_ready.ready ? {
        ready: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_paid_locked_draft_partial): {
    paid: null;
} | {
    locked: null;
} | {
    draft: null;
} | {
    partial: null;
} {
    return value == Variant_paid_locked_draft_partial.paid ? {
        paid: null
    } : value == Variant_paid_locked_draft_partial.locked ? {
        locked: null
    } : value == Variant_paid_locked_draft_partial.draft ? {
        draft: null
    } : value == Variant_paid_locked_draft_partial.partial ? {
        partial: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_inProgress): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == Variant_pending_completed_inProgress.pending ? {
        pending: null
    } : value == Variant_pending_completed_inProgress.completed ? {
        completed: null
    } : value == Variant_pending_completed_inProgress.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
