/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SettingsDTO {
    gstNumber: string;
    address: string;
    defaultLanguage: string;
    shopName: string;
    phone: string;
}
export interface InvoiceItem {
    weight: number;
    total: number;
    rate: number;
    description: string;
    purity: number;
}
export interface InvoiceDTO {
    gst: boolean;
    gstPercent: number;
    language: string;
    notes: string;
    customerId: string;
    items: Array<InvoiceItem>;
    partialPayment: number;
}
export type Time = bigint;
export interface JobOrderUpdateDTO {
    id: string;
    status: Variant_pending_completed_inProgress;
    notes: string;
}
export interface Invoice {
    id: string;
    gst: boolean;
    status: Variant_paid_locked_draft_partial;
    createdAt: Time;
    gstPercent: number;
    amountPaid: number;
    language: string;
    updatedAt: Time;
    totalAmount: number;
    notes: string;
    udhar: number;
    customerId: string;
    items: Array<InvoiceItem>;
    partialPayment: number;
}
export interface JobOrder {
    id: string;
    customerName: string;
    status: Variant_pending_completed_inProgress;
    assignedKaragir: string;
    createdAt: Time;
    dueDate: Time;
    description: string;
    updatedAt: Time;
    notes: string;
}
export interface Customer {
    name: string;
    createdAt: Time;
    address: string;
    phone: string;
}
export interface InvoiceUpdateDTO {
    id: string;
    status: Variant_paid_locked_draft_partial;
}
export interface JobOrderDTO {
    customerName: string;
    assignedKaragir: string;
    dueDate: Time;
    description: string;
}
export interface UserDTO {
    password: string;
    name: string;
    role: Role;
    phone: string;
}
export interface GoldRateDTO {
    ratePerGram: number;
}
export interface CustomerDTO {
    name: string;
    address: string;
    phone: string;
}
export interface UserProfile {
    name: string;
    role: Role;
    phone: string;
}
export enum Role {
    karagir = "karagir",
    manager = "manager",
    owner = "owner",
    staff = "staff"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_paid_locked_draft_partial {
    paid = "paid",
    locked = "locked",
    draft = "draft",
    partial = "partial"
}
export enum Variant_pending_completed_inProgress {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomer(customer: CustomerDTO): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createInvoice(invoice: InvoiceDTO): Promise<string>;
    createJobOrder(job: JobOrderDTO): Promise<string>;
    createUser(userDTO: UserDTO): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(phone: string): Promise<Customer | null>;
    getCustomers(): Promise<Array<CustomerDTO>>;
    getGoldRate(): Promise<GoldRateDTO>;
    getInvoice(id: string): Promise<Invoice | null>;
    getInvoiceCounts(): Promise<{
        total: bigint;
        paid: bigint;
        unpaid: bigint;
    }>;
    getInvoices(): Promise<Array<Invoice>>;
    getInvoicesByCustomer(customerId: string): Promise<Array<Invoice>>;
    getJobOrder(id: string): Promise<JobOrder | null>;
    getJobOrders(): Promise<Array<JobOrder>>;
    getPaidInvoices(): Promise<Array<Invoice>>;
    getPaymentHistory(customerId: string): Promise<Array<Invoice>>;
    getSettings(): Promise<SettingsDTO>;
    getTotalSales(): Promise<number>;
    getTotalUdharPending(): Promise<number>;
    getUdharLedger(): Promise<Array<Invoice>>;
    getUnpaidInvoices(): Promise<Array<Invoice>>;
    getUserProfile(userPrincipal: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    lockInvoice(id: string): Promise<void>;
    login(phone: string, password: string): Promise<UserDTO>;
    receivePayment(invoiceId: string, amount: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateGoldRate(newRate: GoldRateDTO): Promise<void>;
    updateInvoiceStatus(update: InvoiceUpdateDTO): Promise<void>;
    updateJobOrder(update: JobOrderUpdateDTO): Promise<void>;
    updateSettings(newSettings: SettingsDTO): Promise<void>;
}
import type { Customer as _Customer, Invoice as _Invoice, InvoiceItem as _InvoiceItem, InvoiceUpdateDTO as _InvoiceUpdateDTO, JobOrder as _JobOrder, JobOrderUpdateDTO as _JobOrderUpdateDTO, Role as _Role, Time as _Time, UserDTO as _UserDTO, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomer(arg0: CustomerDTO): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createInvoice(arg0: InvoiceDTO): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0);
            return result;
        }
    }
    async createJobOrder(arg0: JobOrderDTO): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobOrder(arg0);
            return result;
        }
    }
    async createUser(arg0: UserDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(to_candid_UserDTO_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(to_candid_UserDTO_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: string): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<CustomerDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getGoldRate(): Promise<GoldRateDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoldRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoldRate();
            return result;
        }
    }
    async getInvoice(arg0: string): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoiceCounts(): Promise<{
        total: bigint;
        paid: bigint;
        unpaid: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceCounts();
            return result;
        }
    }
    async getInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoices();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoices();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByCustomer(arg0: string): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByCustomer(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByCustomer(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobOrder(arg0: string): Promise<JobOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobOrder(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobOrder(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobOrders(): Promise<Array<JobOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobOrders();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobOrders();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaidInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaidInvoices();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaidInvoices();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentHistory(arg0: string): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentHistory(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentHistory(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<SettingsDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getTotalSales(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSales();
            return result;
        }
    }
    async getTotalUdharPending(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalUdharPending();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalUdharPending();
            return result;
        }
    }
    async getUdharLedger(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUdharLedger();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUdharLedger();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnpaidInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnpaidInvoices();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnpaidInvoices();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async lockInvoice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.lockInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockInvoice(arg0);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<UserDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_UserDTO_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_UserDTO_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async receivePayment(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.receivePayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.receivePayment(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateGoldRate(arg0: GoldRateDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoldRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoldRate(arg0);
            return result;
        }
    }
    async updateInvoiceStatus(arg0: InvoiceUpdateDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoiceStatus(to_candid_InvoiceUpdateDTO_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoiceStatus(to_candid_InvoiceUpdateDTO_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJobOrder(arg0: JobOrderUpdateDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobOrder(to_candid_JobOrderUpdateDTO_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobOrder(to_candid_JobOrderUpdateDTO_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSettings(arg0: SettingsDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
}
function from_candid_Invoice_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_JobOrder_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobOrder): JobOrder {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserDTO_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserDTO): UserDTO {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobOrder]): JobOrder | null {
    return value.length === 0 ? null : from_candid_JobOrder_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    gst: boolean;
    status: {
        paid: null;
    } | {
        locked: null;
    } | {
        draft: null;
    } | {
        partial: null;
    };
    createdAt: _Time;
    gstPercent: number;
    amountPaid: number;
    language: string;
    updatedAt: _Time;
    totalAmount: number;
    notes: string;
    udhar: number;
    customerId: string;
    items: Array<_InvoiceItem>;
    partialPayment: number;
}): {
    id: string;
    gst: boolean;
    status: Variant_paid_locked_draft_partial;
    createdAt: Time;
    gstPercent: number;
    amountPaid: number;
    language: string;
    updatedAt: Time;
    totalAmount: number;
    notes: string;
    udhar: number;
    customerId: string;
    items: Array<InvoiceItem>;
    partialPayment: number;
} {
    return {
        id: value.id,
        gst: value.gst,
        status: from_candid_variant_n18(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        gstPercent: value.gstPercent,
        amountPaid: value.amountPaid,
        language: value.language,
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        notes: value.notes,
        udhar: value.udhar,
        customerId: value.customerId,
        items: value.items,
        partialPayment: value.partialPayment
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        inProgress: null;
    };
    assignedKaragir: string;
    createdAt: _Time;
    dueDate: _Time;
    description: string;
    updatedAt: _Time;
    notes: string;
}): {
    id: string;
    customerName: string;
    status: Variant_pending_completed_inProgress;
    assignedKaragir: string;
    createdAt: Time;
    dueDate: Time;
    description: string;
    updatedAt: Time;
    notes: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_variant_n23(_uploadFile, _downloadFile, value.status),
        assignedKaragir: value.assignedKaragir,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        description: value.description,
        updatedAt: value.updatedAt,
        notes: value.notes
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password: string;
    name: string;
    role: _Role;
    phone: string;
}): {
    password: string;
    name: string;
    role: Role;
    phone: string;
} {
    return {
        password: value.password,
        name: value.name,
        role: from_candid_Role_n10(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _Role;
    phone: string;
}): {
    name: string;
    role: Role;
    phone: string;
} {
    return {
        name: value.name,
        role: from_candid_Role_n10(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    karagir: null;
} | {
    manager: null;
} | {
    owner: null;
} | {
    staff: null;
}): Role {
    return "karagir" in value ? Role.karagir : "manager" in value ? Role.manager : "owner" in value ? Role.owner : "staff" in value ? Role.staff : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    locked: null;
} | {
    draft: null;
} | {
    partial: null;
}): Variant_paid_locked_draft_partial {
    return "paid" in value ? Variant_paid_locked_draft_partial.paid : "locked" in value ? Variant_paid_locked_draft_partial.locked : "draft" in value ? Variant_paid_locked_draft_partial.draft : "partial" in value ? Variant_paid_locked_draft_partial.partial : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): Variant_pending_completed_inProgress {
    return "pending" in value ? Variant_pending_completed_inProgress.pending : "completed" in value ? Variant_pending_completed_inProgress.completed : "inProgress" in value ? Variant_pending_completed_inProgress.inProgress : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobOrder>): Array<JobOrder> {
    return value.map((x)=>from_candid_JobOrder_n21(_uploadFile, _downloadFile, x));
}
function to_candid_InvoiceUpdateDTO_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceUpdateDTO): _InvoiceUpdateDTO {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_JobOrderUpdateDTO_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobOrderUpdateDTO): _JobOrderUpdateDTO {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserDTO_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserDTO): _UserDTO {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
    phone: string;
}): {
    name: string;
    role: _Role;
    phone: string;
} {
    return {
        name: value.name,
        role: to_candid_Role_n5(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_paid_locked_draft_partial;
}): {
    id: string;
    status: {
        paid: null;
    } | {
        locked: null;
    } | {
        draft: null;
    } | {
        partial: null;
    };
} {
    return {
        id: value.id,
        status: to_candid_variant_n31(_uploadFile, _downloadFile, value.status)
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_pending_completed_inProgress;
    notes: string;
}): {
    id: string;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        inProgress: null;
    };
    notes: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        notes: value.notes
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password: string;
    name: string;
    role: Role;
    phone: string;
}): {
    password: string;
    name: string;
    role: _Role;
    phone: string;
} {
    return {
        password: value.password,
        name: value.name,
        role: to_candid_Role_n5(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_paid_locked_draft_partial): {
    paid: null;
} | {
    locked: null;
} | {
    draft: null;
} | {
    partial: null;
} {
    return value == Variant_paid_locked_draft_partial.paid ? {
        paid: null
    } : value == Variant_paid_locked_draft_partial.locked ? {
        locked: null
    } : value == Variant_paid_locked_draft_partial.draft ? {
        draft: null
    } : value == Variant_paid_locked_draft_partial.partial ? {
        partial: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_inProgress): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == Variant_pending_completed_inProgress.pending ? {
        pending: null
    } : value == Variant_pending_completed_inProgress.completed ? {
        completed: null
    } : value == Variant_pending_completed_inProgress.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    karagir: null;
} | {
    manager: null;
} | {
    owner: null;
} | {
    staff: null;
} {
    return value == Role.karagir ? {
        karagir: null
    } : value == Role.manager ? {
        manager: null
    } : value == Role.owner ? {
        owner: null
    } : value == Role.staff ? {
        staff: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
